version: "3.9"
services:
  mongoDb:
    image: mongo:4.4.6
    container_name: meu-mongo
    networks:
      - compose-bridge
  
  alurabooks:
    image: aluradocker/alura-books:1.0
    container_name: alurabooks-front
    networks:
      - compose-bridge
    ports:
      - 3000:3000
    depends_on:
      - mongoDb

networks:
  compose-bridge:
    driver: bridge
